# Generated by Django 5.2.1 on 2025-05-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.booking'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
