# Generated by Django 5.2.1 on 2025-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_booking_location_remove_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
